//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package types;

public class MyClass extends com.zeroc.Ice.Value
{
    public MyClass()
    {
    }

    public MyClass(types.Test[] field3, types.Test field4)
    {
        this.field3 = field3;
        this.field4 = field4;
    }

    public types.Test[] field3;

    public types.Test field4;

    public MyClass clone()
    {
        return (MyClass)super.clone();
    }

    public static String ice_staticId()
    {
        return "::types::MyClass";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -5952035756263803801L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        TestsHelper.write(ostr_, field3);
        ostr_.writeSerializable(field4);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        field3 = TestsHelper.read(istr_);
        field4 = istr_.readSerializable(types.Test.class);
        istr_.endSlice();
    }
}
