//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package types;

public class MyStructure implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public int field1;

    public double field2;

    public MyStructure()
    {
    }

    public MyStructure(int field1, double field2)
    {
        this.field1 = field1;
        this.field2 = field2;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        MyStructure r = null;
        if(rhs instanceof MyStructure)
        {
            r = (MyStructure)rhs;
        }

        if(r != null)
        {
            if(this.field1 != r.field1)
            {
                return false;
            }
            if(this.field2 != r.field2)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::types::MyStructure");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, field1);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, field2);
        return h_;
    }

    public MyStructure clone()
    {
        MyStructure c = null;
        try
        {
            c = (MyStructure)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.field1);
        ostr.writeDouble(this.field2);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.field1 = istr.readInt();
        this.field2 = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, MyStructure v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public MyStructure ice_read(com.zeroc.Ice.InputStream istr)
    {
        MyStructure v = new MyStructure();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<MyStructure> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, MyStructure v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(12);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<MyStructure> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(MyStructure.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final MyStructure _nullMarshalValue = new MyStructure();

    /** @hidden */
    public static final long serialVersionUID = 3173842917210455330L;
}
