//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package types;

/**
 * Helper class for marshaling/unmarshaling Tests.
 **/
public final class TestsHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, types.Test[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ostr.writeSerializable(v[i0]);
            }
        }
    }

    public static types.Test[] read(com.zeroc.Ice.InputStream istr)
    {
        final types.Test[] v;
        final int len0 = istr.readAndCheckSeqSize(1);
        v = new types.Test[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = istr.readSerializable(types.Test.class);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<types.Test[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, types.Test[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            TestsHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<types.Test[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            types.Test[] v;
            v = TestsHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
